### ISSUE TITLE
No callback execution when using no function argument

### ISSUE THREAD

**Issue by Vollbrecht** [sixtyfpsui/sixtyfps#769] opened 2021-12-24 15:51 UTC
## Discription
 callback gets not executed when handle function does not use call_by_value.
To illustrate the problem i created the same function twice
``` 
fn render_call_by_value(call_value: i32) -> sixtyfps::Image {...}

fn render_call_void() -> sixtyfps::Image {...}

```

## Expectation
 Both images should get updated each time the callback gets executed.

## Behaviour
Only the function with call_by_value gets updated

For bug reproduction use the following minimal repository:
https://github.com/Vollbrecht/callback-bug

For demonstration purpose both run at the same time, but commenting one function out and only let one run does not change the behavior.

## Workings of the provided example
There is a separate thread that updates an "phase" value into a global mutexed variable. Its used to create the animation effect. The thread also executes `     sixtyfps::invoke_from_event_loop` to update the context.
The appwindow.60 defines both needed callbacks and the two Images that should be drawn.
The main function only  bootstrap the thread,create both callbacks and than run ui.run()

### Software version

sixtyfps 0.1.5

### Operating system

Linux 5.10.0-8-amd64

### Cargo version
```
> cargo --version 
cargo 1.57.0 (b2e52d7ca 2021-10-21)
```

**Comment by ogoffart** [comment] 2021-12-27 08:07
Thanks for the bug report and the reproducable testcase.

What's hapenning is that the engine caches the value of each property, and updates the property only if properties it depends on changes. you have:

```
    // image 1
    source: root.call-by-value(frame_counter);
    // image 2
    source: root.call-void();
```

the image 1 depends on frame_counter so when frame counter changes, it must re-evaluate the source property.
But the image 2 don't have this dependency, so it never re-evaluates it and keep the image in cache.

What this means is that you should either have the image itself as a property which you change, or do like you did and add a dependency.

**Comment by Vollbrecht** [comment] 2021-12-27 11:45
Thank you for analyzing the problem and describing why it is happening.

Its clear to me now how to progress with it, but I wonder what is the best way to mitigate the problem for other people. Should there be some kind of documentation of this behavior in docs/langraf.md in the callback paragraph?

For me it was not obvious because i thought of the Image:source as also something like an internal image property. So i thought why would i need an second property declared for it? Which i understand now is not the case.

I wonder if the .60 compiler should try to detect such behavior and give a warning to the user. Maybe something like: "Warning: source: root.call-void() does not declare an automatically re-evaluated relationship. If you want "this" do "that" " Would this lead to many false positive Warnings?

**Comment by ogoffart** [comment] 2021-12-27 13:15
> Should there be some kind of documentation of this behavior in docs/langraf.md in the callback paragraph?

Yes, probably

> I wonder if the .60 compiler should try to detect such behavior and give a warning to the user. Maybe something like: "Warning: source: root.call-void() does not declare an automatically re-evaluated relationship. If you want "this" do "that" " Would this lead to many false positive Warnings?

I don't think it should because in many case, this is intentional.

**Comment by ogoffart** [comment] 2022-01-03 10:40
I'll close this issue because i don't consider this as a bug.

**Closed by ogoffart** 2022-01-03 10:40 UTC
