### ISSUE TITLE
TextEdit: Lacking on-screen keyboard & IME

### ISSUE THREAD

**Issue by hunger** [sixtyfpsui/sixtyfps#516] opened 2021-09-23 05:50 UTC
From [Reddit](https://www.reddit.com/r/rust/comments/prrpuz/_/hdwwb53):

> And the mobile phone keyboard does not pop up when entering into the line editor. When forced up then IME is not working either.

**Comment by ogoffart** [comment] 2021-09-23 09:39
Duplicate of #215

**Closed by ogoffart** 2021-09-23 09:39 UTC
