### ISSUE TITLE
Panic on `debug_assert_eq!` in `DependencyListHead::mem_move` on exit with qt_backend

### ISSUE THREAD

**Issue by Eijebong** [sixtyfpsui/sixtyfps#732] opened 2021-12-09 14:36 UTC
Versions:

- Rustc: rustc 1.59.0-nightly (e6b883c74 2021-12-08)
- sixtyfps: Current master, e60c144859473142aaa7936be6dcad0556582ffd
- Qt: 5.15.2

Reduced to https://github.com/Eijebong/sixtyfps-debugassert :

```
import { GroupBox } from "sixtyfps_widgets.60";

MainWindow := Window {
    GroupBox {
    }
}
```

To reproduce: Run the app and close it by exiting normally.

Full backtrace:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0x55bba4181290`,
 right: `0x6f62656a69652f65`', /home/eijebong/.cargo/git/checkouts/sixtyfps-1a243e0ff9772996/e60c144/sixtyfps_runtime/corelib/properties.rs:124:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/936238a92b2f9d6e7afe7dda69b4afd903f96399/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/936238a92b2f9d6e7afe7dda69b4afd903f96399/library/core/src/panicking.rs:106:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/936238a92b2f9d6e7afe7dda69b4afd903f96399/library/core/src/panicking.rs:144:5
   4: sixtyfps_corelib::properties::dependency_tracker::DependencyListHead<T>::mem_move
             at /home/eijebong/.cargo/git/checkouts/sixtyfps-1a243e0ff9772996/e60c144/sixtyfps_runtime/corelib/properties.rs:124:17
   5: sixtyfps_corelib::properties::PropertyHandle::remove_binding
             at /home/eijebong/.cargo/git/checkouts/sixtyfps-1a243e0ff9772996/e60c144/sixtyfps_runtime/corelib/properties.rs:475:17
   6: <sixtyfps_corelib::properties::PropertyHandle as core::ops::drop::Drop>::drop
             at /home/eijebong/.cargo/git/checkouts/sixtyfps-1a243e0ff9772996/e60c144/sixtyfps_runtime/corelib/properties.rs:610:9
   7: core::ptr::drop_in_place<sixtyfps_corelib::properties::PropertyHandle>
             at /rustc/936238a92b2f9d6e7afe7dda69b4afd903f96399/library/core/src/ptr/mod.rs:188:1
   8: core::ptr::drop_in_place<sixtyfps_corelib::properties::Property<sixtyfps_corelib::string::SharedString>>
             at /rustc/936238a92b2f9d6e7afe7dda69b4afd903f96399/library/core/src/ptr/mod.rs:188:1
   9: core::ptr::drop_in_place<sixtyfps_rendering_backend_qt::qt_widgets::groupbox::NativeGroupBox>
             at /rustc/936238a92b2f9d6e7afe7dda69b4afd903f96399/library/core/src/ptr/mod.rs:188:1
  10: core::ptr::drop_in_place<sixtyrepro::sixtyfps_generated_MainWindow::InnerMainWindow>
             at /rustc/936238a92b2f9d6e7afe7dda69b4afd903f96399/library/core/src/ptr/mod.rs:188:1
  11: sixtyrepro::sixtyfps_generated_MainWindow::InnerMainWindow::item_tree::VT::drop_in_place
             at ./target/debug/build/sixtyrepro-02bb75e0a45ed0d4/out/mainwindow.rs:302:14
  12: <sixtyfps_corelib::component::Component_vtable_mod::ComponentVTable as vtable::vrc::VTableMetaDropInPlace>::drop_in_place
             at /home/eijebong/.cargo/git/checkouts/sixtyfps-1a243e0ff9772996/e60c144/sixtyfps_runtime/corelib/component.rs:21:1
  13: <vtable::vrc::VRc<VTable,X> as core::ops::drop::Drop>::drop
             at /home/eijebong/.cargo/git/checkouts/sixtyfps-1a243e0ff9772996/e60c144/helper_crates/vtable/src/vrc.rs:112:34
  14: core::ptr::drop_in_place<vtable::vrc::VRc<sixtyfps_corelib::component::Component_vtable_mod::ComponentVTable,sixtyrepro::sixtyfps_generated_MainWindow::InnerMainWindow>>
             at /rustc/936238a92b2f9d6e7afe7dda69b4afd903f96399/library/core/src/ptr/mod.rs:188:1
  15: core::ptr::drop_in_place<sixtyrepro::sixtyfps_generated_MainWindow::MainWindow>
             at /rustc/936238a92b2f9d6e7afe7dda69b4afd903f96399/library/core/src/ptr/mod.rs:188:1
  16: sixtyrepro::main
             at ./src/main.rs:5:1
  17: core::ops::function::FnOnce::call_once
             at /rustc/936238a92b2f9d6e7afe7dda69b4afd903f96399/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by ogoffart** [comment] 2021-12-10 10:05
Thanks for the bug report and the reproducable testcase.
I can reproduce  (and this can also be reproduced by closing the gallery example built with rust)
The problem is appearing because the NativeGroupBox internally has two-ways bindings to a property that the sixtyfps compiler sets as constant. And the code to drop the two ways binding doesn't take in account that the property might be constant.
Will work on a fix.

**Closed** 2021-12-10 10:29 UTC
Labels: bug

**Comment by ogoffart** [comment] 2021-12-10 10:32
This is now fixed.  Thanks again for the report.
