### ISSUE TITLE
Convinient idiom to toggle visibility of elements

### ISSUE THREAD

**Issue by matklad** [sixtyfpsui/sixtyfps#163] opened 2021-02-05 22:13 UTC
I've noticed that the printer demo use `y: root.height` idiom to hide elements:

https://github.com/sixtyfpsui/sixtyfps/blob/master/examples/printerdemo/ui/printerdemo.60#L278-L283

Would be cool to have something more first-class here, the trick seems to interact poorly with layouting. EDIT: that is, setting `y` for a `HorizontalLayout` doesn't seem to take effect

**Comment by ogoffart** [comment] 2021-02-08 07:19
Closing as duplicate of https://github.com/sixtyfpsui/sixtyfps/issues/163

**Closed by ogoffart** 2021-02-08 07:19 UTC

**Comment by ogoffart** [comment] 2021-02-08 07:21
I meant https://github.com/sixtyfpsui/sixtyfps/issues/141
